puts "🌱 Seeding spices..."
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

r1 = Restaraunt.create(name: "Boca Bistro", cuisine_type: "Mediterranean", rating: Faker::Number.within(range: 1..10), delivery: true)
r2 = Restaraunt.create(name: "Chianti Ristorante", cuisine_type: "Italian", rating: Faker::Number.within(range: 1..10), delivery: true)
r3 = Restaraunt.create(name: "Hatties", cuisine_type: "American", rating: Faker::Number.within(range: 1..10), delivery: false)
r4 = Restaraunt.create(name: "15 Church", cuisine_type: "American", rating: Faker::Number.within(range: 1..10), delivery: true)
r5 = Restaraunt.create(name: "Harvey's Restaraunt & Bar", cuisine_type: "Irish", rating: Faker::Number.within(range: 1..10), delivery: false)
r6 = Restaraunt.create(name: "The Mouzon House", cuisine_type: "French", rating: Faker::Number.within(range: 1..10), delivery: false)
r7 = Restaraunt.create(name: "Scallions", cuisine_type: "American", rating: Faker::Number.within(range: 1..10), delivery: true)
r8 = Restaraunt.create(name: "Ripe Tomato", cuisine_type: "Italian", rating: Faker::Number.within(range: 1..10), delivery: true)
r9 = Restaraunt.create(name: "The Brook Tavern", cuisine_type: "American", rating: Faker::Number.within(range: 1..10), delivery: false)
r10 = Restaraunt.create(name: "Karavalli", cuisine_type: "Indian", rating: Faker::Number.within(range: 1..10), delivery: true)

review1 = Review.create(content: "The food was delicious")
review2 = Review.create(content: "The food was terrible")
review3 = Review.create(content: "The atmosphere was very nice and calming")
review4 = Review.create(content: "The final bill for the food was much higher than I thought it would be")
review5 = Review.create(content: "The staff was very friendly and the food was amazing")
review6 = Review.create(content: "I would highly recommend eating here if you are in town")
review7 = Review.create(content: "The food was reasonably priced")
review8 = Review.create(content: "I went here for my birthday and the entire staff sang me happy birthday!")
review9 = Review.create(content: "The food was perfectly cooked")
review10 = Review.create(content: "Make sure that you save room for desert. The lava cake was absolutely delicious")
review11 = Review.create(content: "The food came out cold and our waiter was not very attentive to us")
review12 = Review.create(content: "I can't wait to come back here with my entire family")
review13 = Review.create(content: "The food was not that good, but the prices were very resonable")
review14 = Review.create(content: "The best place to eat in town!")
review15 = Review.create(content: "The prices are way to high and parking is very hard to find. I would recommend only coming here later at night")
review16 = Review.create(content: "The drinks were very well priced and it was such a fun atmosphere")
review17 = Review.create(content: "I will be coming back to this place next time I am in town")
review18 = Review.create(content: "The appetizers took way to long to come out, but overall, we had a really good time")
review19 = Review.create(content: "I have been raving about this place to all my friends and family!")
review20 = Review.create(content: "Could not have asked for a better experience or better service. This is by far one of my favorite restaraunts!")

user1 = User.create(name: Faker::Name.name)
user2 = User.create(name: Faker::Name.name)
user3 = User.create(name: Faker::Name.name)
user4 = User.create(name: Faker::Name.name)
user5 = User.create(name: Faker::Name.name)
user6 = User.create(name: Faker::Name.name)
user7 = User.create(name: Faker::Name.name)
user8 = User.create(name: Faker::Name.name)
user9 = User.create(name: Faker::Name.name)
user10 = User.create(name: Faker::Name.name)
user11 = User.create(name: Faker::Name.name)
user12 = User.create(name: Faker::Name.name)
user13 = User.create(name: Faker::Name.name)
user14 = User.create(name: Faker::Name.name)
user15 = User.create(name: Faker::Name.name)
user16 = User.create(name: Faker::Name.name)
user17 = User.create(name: Faker::Name.name)
user18 = User.create(name: Faker::Name.name)
user19 = User.create(name: Faker::Name.name)
user20 = User.create(name: Faker::Name.name)
user21 = User.create(name: Faker::Name.name)
user22 = User.create(name: Faker::Name.name)
user23 = User.create(name: Faker::Name.name)
user24 = User.create(name: Faker::Name.name)
user25 = User.create(name: Faker::Name.name)
user26 = User.create(name: Faker::Name.name)
user27 = User.create(name: Faker::Name.name)
user28 = User.create(name: Faker::Name.name)
user29 = User.create(name: Faker::Name.name)
user30 = User.create(name: Faker::Name.name)
user31 = User.create(name: Faker::Name.name)
user32 = User.create(name: Faker::Name.name)
user33 = User.create(name: Faker::Name.name)
user34 = User.create(name: Faker::Name.name)
user35 = User.create(name: Faker::Name.name)
user36 = User.create(name: Faker::Name.name)
user37 = User.create(name: Faker::Name.name)
user38 = User.create(name: Faker::Name.name)
user39 = User.create(name: Faker::Name.name)
user40 = User.create(name: Faker::Name.name)



puts "✅ Done seeding!"